// <auto-generated />
using System;
using Lab2_Programming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab2_Programming.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab2_Programming.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<double?>("AvarageGrade")
                        .HasColumnType("double precision")
                        .HasColumnName("avarage_grade");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("ParentsPhone")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("parents_phone");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("third_name");

                    b.HasKey("StudentId")
                        .HasName("student_pkey");

                    b.HasIndex("TeacherId");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Lab2_Programming.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Salary")
                        .HasColumnType("integer")
                        .HasColumnName("salary");

                    b.Property<string>("TeacherClass")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("teacher_class");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("third_name");

                    b.HasKey("TeacherId")
                        .HasName("teacher_pkey");

                    b.ToTable("teacher", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            LastName = "Шевченко",
                            Name = "Олена",
                            PhoneNumber = "0991234567",
                            Salary = 15000,
                            TeacherClass = "10-А",
                            ThirdName = "Іванівна"
                        },
                        new
                        {
                            TeacherId = 2,
                            LastName = "Коваленко",
                            Name = "Ігор",
                            PhoneNumber = "0987654321",
                            Salary = 16000,
                            TeacherClass = "11-Б",
                            ThirdName = "Петрович"
                        },
                        new
                        {
                            TeacherId = 3,
                            LastName = "Чайка",
                            Name = "Василь",
                            PhoneNumber = "0995314367",
                            Salary = 15000,
                            TeacherClass = "9-Б",
                            ThirdName = "Олегович"
                        });
                });

            modelBuilder.Entity("Lab2_Programming.Models.Student", b =>
                {
                    b.HasOne("Lab2_Programming.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("student_teacher_id_fkey");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Lab2_Programming.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
